service: lambda-template-js

frameworkVersion: '3'

# Serverless plugins
plugins:
  - serverless-offline

# Cloud Provider
provider:
  name: aws
  runtime: nodejs12.x

# Functions
functions:
  hello:
    handler: dist/index.sendHello
    events: 
      - http:
          path: hello
          method: get
  create-notification:
    environment:
      DATABASE_URL: file:./dev.db
    handler: dist/index.createNotification
    events: 
      - http:
          path: notifications
          method: post
  get-from-recipient:
    environment:
      DATABASE_URL: file:./dev.db
    handler: dist/index.getFromRecipient
    events: 
      - http:
          path: notifications/from/{recipientId}
          method: get
