service: lambda-template-js

frameworkVersion: '3'

# Serverless plugins
plugins:
  - serverless-offline

# Cloud Provider
provider:
  name: aws
  runtime: nodejs12.x

# Functions
functions:
  hello:
    handler: dist/index.sendHello
    events: 
      - http:
          path: hello
          method: get
  create-notification:
    environment:
      DATABASE_URL: file:../prisma/dev.db
    handler: dist/index.createNotification
    events: 
      - http:
          path: notifications
          method: post
  get-from-recipient:
    environment:
      DATABASE_URL: file:../prisma/dev.db
    handler: dist/index.getFromRecipient
    events: 
      - http:
          path: notifications/from/{recipientId}
          method: get
  count-from-recipient:
    environment:
      DATABASE_URL: file:../prisma/dev.db
    handler: dist/index.countFromRecipient
    events: 
      - http:
          path: notifications/count/from/{recipientId}
          method: get
  cancel-notification:
    environment:
      DATABASE_URL: file:../prisma/dev.db
    handler: dist/index.cancelNotification
    events: 
      - http:
          path: notifications/{notificationId}/cancel
          method: patch
  read-notification:
    environment:
      DATABASE_URL: file:../prisma/dev.db
    handler: dist/index.readNotification
    events: 
      - http:
          path: notifications/{notificationId}/read
          method: patch
  unread-notification:
    environment:
      DATABASE_URL: file:../prisma/dev.db
    handler: dist/index.unreadNotification
    events: 
      - http:
          path: notifications/{notificationId}/unread
          method: patch
